<a href="https://colab.research.google.com/github/ArseniyKoz/uni.ml/blob/t2p/practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[4, 3, 18],
              [22, 11, 2],
              [0, 13, 3]])
X

array([[ 4,  3, 18],
       [22, 11,  2],
       [ 0, 13,  3]])

In [ ]:
X = np.random.normal(loc = 5, scale = 1, size = (6,3))
X

array([[4.71013714, 5.79755513, 4.75874114],
       [5.41687701, 5.91455488, 6.47442018],
       [6.47724974, 4.23987817, 5.01836541],
       [4.629439  , 5.63263188, 6.87616259],
       [4.55976239, 4.89631115, 4.63642933],
       [4.06728583, 5.22030026, 5.46503818]])

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving proceeds21.csv to proceeds21.csv


In [ ]:
import csv
import pandas as pd
data = pd.read_csv('proceeds21.csv', index_col='Month')
print(data)

       Department1  Department2  Department3  Department4
Month                                                    
m1             100           18          454           68
m2              32           54          545           11
m3              12           11           14           17
m4              54           54          121           31
m5             333           11           27            8
m6             123           33           24            5
m7              11           14           17           11
m8             111          121          111          211
m9             100           11           74           15
m10             64           65           68           11
m11             75           58           98           44
m12            113          211          118          144


In [ ]:
X_test = data[['Department1', 'Department2','Department3','Department4']].values
X_test

array([[100,  18, 454,  68],
       [ 32,  54, 545,  11],
       [ 12,  11,  14,  17],
       [ 54,  54, 121,  31],
       [333,  11,  27,   8],
       [123,  33,  24,   5],
       [ 11,  14,  17,  11],
       [111, 121, 111, 211],
       [100,  11,  74,  15],
       [ 64,  65,  68,  11],
       [ 75,  58,  98,  44],
       [113, 211, 118, 144]])

In [ ]:
# В какой месяц суммарная выручка по отделам превысила 400
r = np.sum(X_test, axis = 1)
#print(r)
print('ans =',  data.index.values[np.nonzero(r > 400)])

ans = ['m1' 'm2' 'm8' 'm12']


In [ ]:
# Имя отдела с максимальной средней выручкой за год
means = np.mean(X_test, 0)
#print(r)
print('ans =', data.columns.values[np.argmax(means)])

ans = Department3


In [ ]:
# Имя отдела с максимальной величиной стандартного отклонения прибыли
sdp = np.std(X_test, 0)
#print(sdp)
print('ans =', data.columns.values[np.argmax(sdp)])

ans = Department3


In [ ]:
r = np.sum(X_test, axis = 1)
data.index.values[np.argmax(r)]

'm2'

# Новый раздел